// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stringdb.proto

#ifndef PROTOBUF_stringdb_2eproto__INCLUDED
#define PROTOBUF_stringdb_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_stringdb_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[5];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsRequest_RequestGetValueImpl();
void InitDefaultsRequest_RequestGetValue();
void InitDefaultsRequest_RequestSetValueImpl();
void InitDefaultsRequest_RequestSetValue();
void InitDefaultsRequest_RequestCountValuesImpl();
void InitDefaultsRequest_RequestCountValues();
void InitDefaultsRequestImpl();
void InitDefaultsRequest();
void InitDefaultsResponseImpl();
void InitDefaultsResponse();
inline void InitDefaults() {
  InitDefaultsRequest_RequestGetValue();
  InitDefaultsRequest_RequestSetValue();
  InitDefaultsRequest_RequestCountValues();
  InitDefaultsRequest();
  InitDefaultsResponse();
}
}  // namespace protobuf_stringdb_2eproto
namespace stringdb {
class Request;
class RequestDefaultTypeInternal;
extern RequestDefaultTypeInternal _Request_default_instance_;
class Request_RequestCountValues;
class Request_RequestCountValuesDefaultTypeInternal;
extern Request_RequestCountValuesDefaultTypeInternal _Request_RequestCountValues_default_instance_;
class Request_RequestGetValue;
class Request_RequestGetValueDefaultTypeInternal;
extern Request_RequestGetValueDefaultTypeInternal _Request_RequestGetValue_default_instance_;
class Request_RequestSetValue;
class Request_RequestSetValueDefaultTypeInternal;
extern Request_RequestSetValueDefaultTypeInternal _Request_RequestSetValue_default_instance_;
class Response;
class ResponseDefaultTypeInternal;
extern ResponseDefaultTypeInternal _Response_default_instance_;
}  // namespace stringdb
namespace stringdb {

enum Request_RequestType {
  Request_RequestType_GET_VALUE = 1,
  Request_RequestType_SET_VALUE = 2,
  Request_RequestType_COUNT_VALUES = 3
};
bool Request_RequestType_IsValid(int value);
const Request_RequestType Request_RequestType_RequestType_MIN = Request_RequestType_GET_VALUE;
const Request_RequestType Request_RequestType_RequestType_MAX = Request_RequestType_COUNT_VALUES;
const int Request_RequestType_RequestType_ARRAYSIZE = Request_RequestType_RequestType_MAX + 1;

const ::google::protobuf::EnumDescriptor* Request_RequestType_descriptor();
inline const ::std::string& Request_RequestType_Name(Request_RequestType value) {
  return ::google::protobuf::internal::NameOfEnum(
    Request_RequestType_descriptor(), value);
}
inline bool Request_RequestType_Parse(
    const ::std::string& name, Request_RequestType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Request_RequestType>(
    Request_RequestType_descriptor(), name, value);
}
// ===================================================================

class Request_RequestGetValue : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:stringdb.Request.RequestGetValue) */ {
 public:
  Request_RequestGetValue();
  virtual ~Request_RequestGetValue();

  Request_RequestGetValue(const Request_RequestGetValue& from);

  inline Request_RequestGetValue& operator=(const Request_RequestGetValue& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Request_RequestGetValue(Request_RequestGetValue&& from) noexcept
    : Request_RequestGetValue() {
    *this = ::std::move(from);
  }

  inline Request_RequestGetValue& operator=(Request_RequestGetValue&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Request_RequestGetValue& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Request_RequestGetValue* internal_default_instance() {
    return reinterpret_cast<const Request_RequestGetValue*>(
               &_Request_RequestGetValue_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(Request_RequestGetValue* other);
  friend void swap(Request_RequestGetValue& a, Request_RequestGetValue& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Request_RequestGetValue* New() const PROTOBUF_FINAL { return New(NULL); }

  Request_RequestGetValue* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Request_RequestGetValue& from);
  void MergeFrom(const Request_RequestGetValue& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Request_RequestGetValue* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string key = 1;
  bool has_key() const;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  const ::std::string& key() const;
  void set_key(const ::std::string& value);
  #if LANG_CXX11
  void set_key(::std::string&& value);
  #endif
  void set_key(const char* value);
  void set_key(const char* value, size_t size);
  ::std::string* mutable_key();
  ::std::string* release_key();
  void set_allocated_key(::std::string* key);

  // @@protoc_insertion_point(class_scope:stringdb.Request.RequestGetValue)
 private:
  void set_has_key();
  void clear_has_key();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr key_;
  friend struct ::protobuf_stringdb_2eproto::TableStruct;
  friend void ::protobuf_stringdb_2eproto::InitDefaultsRequest_RequestGetValueImpl();
};
// -------------------------------------------------------------------

class Request_RequestSetValue : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:stringdb.Request.RequestSetValue) */ {
 public:
  Request_RequestSetValue();
  virtual ~Request_RequestSetValue();

  Request_RequestSetValue(const Request_RequestSetValue& from);

  inline Request_RequestSetValue& operator=(const Request_RequestSetValue& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Request_RequestSetValue(Request_RequestSetValue&& from) noexcept
    : Request_RequestSetValue() {
    *this = ::std::move(from);
  }

  inline Request_RequestSetValue& operator=(Request_RequestSetValue&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Request_RequestSetValue& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Request_RequestSetValue* internal_default_instance() {
    return reinterpret_cast<const Request_RequestSetValue*>(
               &_Request_RequestSetValue_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(Request_RequestSetValue* other);
  friend void swap(Request_RequestSetValue& a, Request_RequestSetValue& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Request_RequestSetValue* New() const PROTOBUF_FINAL { return New(NULL); }

  Request_RequestSetValue* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Request_RequestSetValue& from);
  void MergeFrom(const Request_RequestSetValue& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Request_RequestSetValue* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string key = 1;
  bool has_key() const;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  const ::std::string& key() const;
  void set_key(const ::std::string& value);
  #if LANG_CXX11
  void set_key(::std::string&& value);
  #endif
  void set_key(const char* value);
  void set_key(const char* value, size_t size);
  ::std::string* mutable_key();
  ::std::string* release_key();
  void set_allocated_key(::std::string* key);

  // required string value = 2;
  bool has_value() const;
  void clear_value();
  static const int kValueFieldNumber = 2;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  #if LANG_CXX11
  void set_value(::std::string&& value);
  #endif
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // @@protoc_insertion_point(class_scope:stringdb.Request.RequestSetValue)
 private:
  void set_has_key();
  void clear_has_key();
  void set_has_value();
  void clear_has_value();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr key_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  friend struct ::protobuf_stringdb_2eproto::TableStruct;
  friend void ::protobuf_stringdb_2eproto::InitDefaultsRequest_RequestSetValueImpl();
};
// -------------------------------------------------------------------

class Request_RequestCountValues : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:stringdb.Request.RequestCountValues) */ {
 public:
  Request_RequestCountValues();
  virtual ~Request_RequestCountValues();

  Request_RequestCountValues(const Request_RequestCountValues& from);

  inline Request_RequestCountValues& operator=(const Request_RequestCountValues& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Request_RequestCountValues(Request_RequestCountValues&& from) noexcept
    : Request_RequestCountValues() {
    *this = ::std::move(from);
  }

  inline Request_RequestCountValues& operator=(Request_RequestCountValues&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Request_RequestCountValues& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Request_RequestCountValues* internal_default_instance() {
    return reinterpret_cast<const Request_RequestCountValues*>(
               &_Request_RequestCountValues_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(Request_RequestCountValues* other);
  friend void swap(Request_RequestCountValues& a, Request_RequestCountValues& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Request_RequestCountValues* New() const PROTOBUF_FINAL { return New(NULL); }

  Request_RequestCountValues* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Request_RequestCountValues& from);
  void MergeFrom(const Request_RequestCountValues& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Request_RequestCountValues* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:stringdb.Request.RequestCountValues)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  friend struct ::protobuf_stringdb_2eproto::TableStruct;
  friend void ::protobuf_stringdb_2eproto::InitDefaultsRequest_RequestCountValuesImpl();
};
// -------------------------------------------------------------------

class Request : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:stringdb.Request) */ {
 public:
  Request();
  virtual ~Request();

  Request(const Request& from);

  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Request(Request&& from) noexcept
    : Request() {
    *this = ::std::move(from);
  }

  inline Request& operator=(Request&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Request& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Request* internal_default_instance() {
    return reinterpret_cast<const Request*>(
               &_Request_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(Request* other);
  friend void swap(Request& a, Request& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Request* New() const PROTOBUF_FINAL { return New(NULL); }

  Request* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Request& from);
  void MergeFrom(const Request& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Request* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef Request_RequestGetValue RequestGetValue;
  typedef Request_RequestSetValue RequestSetValue;
  typedef Request_RequestCountValues RequestCountValues;

  typedef Request_RequestType RequestType;
  static const RequestType GET_VALUE =
    Request_RequestType_GET_VALUE;
  static const RequestType SET_VALUE =
    Request_RequestType_SET_VALUE;
  static const RequestType COUNT_VALUES =
    Request_RequestType_COUNT_VALUES;
  static inline bool RequestType_IsValid(int value) {
    return Request_RequestType_IsValid(value);
  }
  static const RequestType RequestType_MIN =
    Request_RequestType_RequestType_MIN;
  static const RequestType RequestType_MAX =
    Request_RequestType_RequestType_MAX;
  static const int RequestType_ARRAYSIZE =
    Request_RequestType_RequestType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  RequestType_descriptor() {
    return Request_RequestType_descriptor();
  }
  static inline const ::std::string& RequestType_Name(RequestType value) {
    return Request_RequestType_Name(value);
  }
  static inline bool RequestType_Parse(const ::std::string& name,
      RequestType* value) {
    return Request_RequestType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .stringdb.Request.RequestGetValue request_get_value = 21;
  bool has_request_get_value() const;
  void clear_request_get_value();
  static const int kRequestGetValueFieldNumber = 21;
  const ::stringdb::Request_RequestGetValue& request_get_value() const;
  ::stringdb::Request_RequestGetValue* release_request_get_value();
  ::stringdb::Request_RequestGetValue* mutable_request_get_value();
  void set_allocated_request_get_value(::stringdb::Request_RequestGetValue* request_get_value);

  // optional .stringdb.Request.RequestSetValue request_set_value = 22;
  bool has_request_set_value() const;
  void clear_request_set_value();
  static const int kRequestSetValueFieldNumber = 22;
  const ::stringdb::Request_RequestSetValue& request_set_value() const;
  ::stringdb::Request_RequestSetValue* release_request_set_value();
  ::stringdb::Request_RequestSetValue* mutable_request_set_value();
  void set_allocated_request_set_value(::stringdb::Request_RequestSetValue* request_set_value);

  // optional .stringdb.Request.RequestCountValues request_count_values = 23;
  bool has_request_count_values() const;
  void clear_request_count_values();
  static const int kRequestCountValuesFieldNumber = 23;
  const ::stringdb::Request_RequestCountValues& request_count_values() const;
  ::stringdb::Request_RequestCountValues* release_request_count_values();
  ::stringdb::Request_RequestCountValues* mutable_request_count_values();
  void set_allocated_request_count_values(::stringdb::Request_RequestCountValues* request_count_values);

  // required .stringdb.Request.RequestType type = 1;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::stringdb::Request_RequestType type() const;
  void set_type(::stringdb::Request_RequestType value);

  // @@protoc_insertion_point(class_scope:stringdb.Request)
 private:
  void set_has_type();
  void clear_has_type();
  void set_has_request_get_value();
  void clear_has_request_get_value();
  void set_has_request_set_value();
  void clear_has_request_set_value();
  void set_has_request_count_values();
  void clear_has_request_count_values();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::stringdb::Request_RequestGetValue* request_get_value_;
  ::stringdb::Request_RequestSetValue* request_set_value_;
  ::stringdb::Request_RequestCountValues* request_count_values_;
  int type_;
  friend struct ::protobuf_stringdb_2eproto::TableStruct;
  friend void ::protobuf_stringdb_2eproto::InitDefaultsRequestImpl();
};
// -------------------------------------------------------------------

class Response : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:stringdb.Response) */ {
 public:
  Response();
  virtual ~Response();

  Response(const Response& from);

  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Response(Response&& from) noexcept
    : Response() {
    *this = ::std::move(from);
  }

  inline Response& operator=(Response&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Response& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Response* internal_default_instance() {
    return reinterpret_cast<const Response*>(
               &_Response_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(Response* other);
  friend void swap(Response& a, Response& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Response* New() const PROTOBUF_FINAL { return New(NULL); }

  Response* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Response& from);
  void MergeFrom(const Response& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Response* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string value = 1;
  bool has_value() const;
  void clear_value();
  static const int kValueFieldNumber = 1;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  #if LANG_CXX11
  void set_value(::std::string&& value);
  #endif
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // @@protoc_insertion_point(class_scope:stringdb.Response)
 private:
  void set_has_value();
  void clear_has_value();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  friend struct ::protobuf_stringdb_2eproto::TableStruct;
  friend void ::protobuf_stringdb_2eproto::InitDefaultsResponseImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Request_RequestGetValue

// required string key = 1;
inline bool Request_RequestGetValue::has_key() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Request_RequestGetValue::set_has_key() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Request_RequestGetValue::clear_has_key() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Request_RequestGetValue::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_key();
}
inline const ::std::string& Request_RequestGetValue::key() const {
  // @@protoc_insertion_point(field_get:stringdb.Request.RequestGetValue.key)
  return key_.GetNoArena();
}
inline void Request_RequestGetValue::set_key(const ::std::string& value) {
  set_has_key();
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:stringdb.Request.RequestGetValue.key)
}
#if LANG_CXX11
inline void Request_RequestGetValue::set_key(::std::string&& value) {
  set_has_key();
  key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:stringdb.Request.RequestGetValue.key)
}
#endif
inline void Request_RequestGetValue::set_key(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_key();
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:stringdb.Request.RequestGetValue.key)
}
inline void Request_RequestGetValue::set_key(const char* value, size_t size) {
  set_has_key();
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:stringdb.Request.RequestGetValue.key)
}
inline ::std::string* Request_RequestGetValue::mutable_key() {
  set_has_key();
  // @@protoc_insertion_point(field_mutable:stringdb.Request.RequestGetValue.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Request_RequestGetValue::release_key() {
  // @@protoc_insertion_point(field_release:stringdb.Request.RequestGetValue.key)
  clear_has_key();
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Request_RequestGetValue::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    set_has_key();
  } else {
    clear_has_key();
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:stringdb.Request.RequestGetValue.key)
}

// -------------------------------------------------------------------

// Request_RequestSetValue

// required string key = 1;
inline bool Request_RequestSetValue::has_key() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Request_RequestSetValue::set_has_key() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Request_RequestSetValue::clear_has_key() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Request_RequestSetValue::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_key();
}
inline const ::std::string& Request_RequestSetValue::key() const {
  // @@protoc_insertion_point(field_get:stringdb.Request.RequestSetValue.key)
  return key_.GetNoArena();
}
inline void Request_RequestSetValue::set_key(const ::std::string& value) {
  set_has_key();
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:stringdb.Request.RequestSetValue.key)
}
#if LANG_CXX11
inline void Request_RequestSetValue::set_key(::std::string&& value) {
  set_has_key();
  key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:stringdb.Request.RequestSetValue.key)
}
#endif
inline void Request_RequestSetValue::set_key(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_key();
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:stringdb.Request.RequestSetValue.key)
}
inline void Request_RequestSetValue::set_key(const char* value, size_t size) {
  set_has_key();
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:stringdb.Request.RequestSetValue.key)
}
inline ::std::string* Request_RequestSetValue::mutable_key() {
  set_has_key();
  // @@protoc_insertion_point(field_mutable:stringdb.Request.RequestSetValue.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Request_RequestSetValue::release_key() {
  // @@protoc_insertion_point(field_release:stringdb.Request.RequestSetValue.key)
  clear_has_key();
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Request_RequestSetValue::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    set_has_key();
  } else {
    clear_has_key();
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:stringdb.Request.RequestSetValue.key)
}

// required string value = 2;
inline bool Request_RequestSetValue::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Request_RequestSetValue::set_has_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Request_RequestSetValue::clear_has_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Request_RequestSetValue::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_value();
}
inline const ::std::string& Request_RequestSetValue::value() const {
  // @@protoc_insertion_point(field_get:stringdb.Request.RequestSetValue.value)
  return value_.GetNoArena();
}
inline void Request_RequestSetValue::set_value(const ::std::string& value) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:stringdb.Request.RequestSetValue.value)
}
#if LANG_CXX11
inline void Request_RequestSetValue::set_value(::std::string&& value) {
  set_has_value();
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:stringdb.Request.RequestSetValue.value)
}
#endif
inline void Request_RequestSetValue::set_value(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:stringdb.Request.RequestSetValue.value)
}
inline void Request_RequestSetValue::set_value(const char* value, size_t size) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:stringdb.Request.RequestSetValue.value)
}
inline ::std::string* Request_RequestSetValue::mutable_value() {
  set_has_value();
  // @@protoc_insertion_point(field_mutable:stringdb.Request.RequestSetValue.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Request_RequestSetValue::release_value() {
  // @@protoc_insertion_point(field_release:stringdb.Request.RequestSetValue.value)
  clear_has_value();
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Request_RequestSetValue::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    set_has_value();
  } else {
    clear_has_value();
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:stringdb.Request.RequestSetValue.value)
}

// -------------------------------------------------------------------

// Request_RequestCountValues

// -------------------------------------------------------------------

// Request

// required .stringdb.Request.RequestType type = 1;
inline bool Request::has_type() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Request::set_has_type() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Request::clear_has_type() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Request::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::stringdb::Request_RequestType Request::type() const {
  // @@protoc_insertion_point(field_get:stringdb.Request.type)
  return static_cast< ::stringdb::Request_RequestType >(type_);
}
inline void Request::set_type(::stringdb::Request_RequestType value) {
  assert(::stringdb::Request_RequestType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:stringdb.Request.type)
}

// optional .stringdb.Request.RequestGetValue request_get_value = 21;
inline bool Request::has_request_get_value() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Request::set_has_request_get_value() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Request::clear_has_request_get_value() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Request::clear_request_get_value() {
  if (request_get_value_ != NULL) request_get_value_->Clear();
  clear_has_request_get_value();
}
inline const ::stringdb::Request_RequestGetValue& Request::request_get_value() const {
  const ::stringdb::Request_RequestGetValue* p = request_get_value_;
  // @@protoc_insertion_point(field_get:stringdb.Request.request_get_value)
  return p != NULL ? *p : *reinterpret_cast<const ::stringdb::Request_RequestGetValue*>(
      &::stringdb::_Request_RequestGetValue_default_instance_);
}
inline ::stringdb::Request_RequestGetValue* Request::release_request_get_value() {
  // @@protoc_insertion_point(field_release:stringdb.Request.request_get_value)
  clear_has_request_get_value();
  ::stringdb::Request_RequestGetValue* temp = request_get_value_;
  request_get_value_ = NULL;
  return temp;
}
inline ::stringdb::Request_RequestGetValue* Request::mutable_request_get_value() {
  set_has_request_get_value();
  if (request_get_value_ == NULL) {
    request_get_value_ = new ::stringdb::Request_RequestGetValue;
  }
  // @@protoc_insertion_point(field_mutable:stringdb.Request.request_get_value)
  return request_get_value_;
}
inline void Request::set_allocated_request_get_value(::stringdb::Request_RequestGetValue* request_get_value) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete request_get_value_;
  }
  if (request_get_value) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      request_get_value = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, request_get_value, submessage_arena);
    }
    set_has_request_get_value();
  } else {
    clear_has_request_get_value();
  }
  request_get_value_ = request_get_value;
  // @@protoc_insertion_point(field_set_allocated:stringdb.Request.request_get_value)
}

// optional .stringdb.Request.RequestSetValue request_set_value = 22;
inline bool Request::has_request_set_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Request::set_has_request_set_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Request::clear_has_request_set_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Request::clear_request_set_value() {
  if (request_set_value_ != NULL) request_set_value_->Clear();
  clear_has_request_set_value();
}
inline const ::stringdb::Request_RequestSetValue& Request::request_set_value() const {
  const ::stringdb::Request_RequestSetValue* p = request_set_value_;
  // @@protoc_insertion_point(field_get:stringdb.Request.request_set_value)
  return p != NULL ? *p : *reinterpret_cast<const ::stringdb::Request_RequestSetValue*>(
      &::stringdb::_Request_RequestSetValue_default_instance_);
}
inline ::stringdb::Request_RequestSetValue* Request::release_request_set_value() {
  // @@protoc_insertion_point(field_release:stringdb.Request.request_set_value)
  clear_has_request_set_value();
  ::stringdb::Request_RequestSetValue* temp = request_set_value_;
  request_set_value_ = NULL;
  return temp;
}
inline ::stringdb::Request_RequestSetValue* Request::mutable_request_set_value() {
  set_has_request_set_value();
  if (request_set_value_ == NULL) {
    request_set_value_ = new ::stringdb::Request_RequestSetValue;
  }
  // @@protoc_insertion_point(field_mutable:stringdb.Request.request_set_value)
  return request_set_value_;
}
inline void Request::set_allocated_request_set_value(::stringdb::Request_RequestSetValue* request_set_value) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete request_set_value_;
  }
  if (request_set_value) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      request_set_value = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, request_set_value, submessage_arena);
    }
    set_has_request_set_value();
  } else {
    clear_has_request_set_value();
  }
  request_set_value_ = request_set_value;
  // @@protoc_insertion_point(field_set_allocated:stringdb.Request.request_set_value)
}

// optional .stringdb.Request.RequestCountValues request_count_values = 23;
inline bool Request::has_request_count_values() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Request::set_has_request_count_values() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Request::clear_has_request_count_values() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Request::clear_request_count_values() {
  if (request_count_values_ != NULL) request_count_values_->Clear();
  clear_has_request_count_values();
}
inline const ::stringdb::Request_RequestCountValues& Request::request_count_values() const {
  const ::stringdb::Request_RequestCountValues* p = request_count_values_;
  // @@protoc_insertion_point(field_get:stringdb.Request.request_count_values)
  return p != NULL ? *p : *reinterpret_cast<const ::stringdb::Request_RequestCountValues*>(
      &::stringdb::_Request_RequestCountValues_default_instance_);
}
inline ::stringdb::Request_RequestCountValues* Request::release_request_count_values() {
  // @@protoc_insertion_point(field_release:stringdb.Request.request_count_values)
  clear_has_request_count_values();
  ::stringdb::Request_RequestCountValues* temp = request_count_values_;
  request_count_values_ = NULL;
  return temp;
}
inline ::stringdb::Request_RequestCountValues* Request::mutable_request_count_values() {
  set_has_request_count_values();
  if (request_count_values_ == NULL) {
    request_count_values_ = new ::stringdb::Request_RequestCountValues;
  }
  // @@protoc_insertion_point(field_mutable:stringdb.Request.request_count_values)
  return request_count_values_;
}
inline void Request::set_allocated_request_count_values(::stringdb::Request_RequestCountValues* request_count_values) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete request_count_values_;
  }
  if (request_count_values) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      request_count_values = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, request_count_values, submessage_arena);
    }
    set_has_request_count_values();
  } else {
    clear_has_request_count_values();
  }
  request_count_values_ = request_count_values;
  // @@protoc_insertion_point(field_set_allocated:stringdb.Request.request_count_values)
}

// -------------------------------------------------------------------

// Response

// required string value = 1;
inline bool Response::has_value() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Response::set_has_value() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Response::clear_has_value() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Response::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_value();
}
inline const ::std::string& Response::value() const {
  // @@protoc_insertion_point(field_get:stringdb.Response.value)
  return value_.GetNoArena();
}
inline void Response::set_value(const ::std::string& value) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:stringdb.Response.value)
}
#if LANG_CXX11
inline void Response::set_value(::std::string&& value) {
  set_has_value();
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:stringdb.Response.value)
}
#endif
inline void Response::set_value(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:stringdb.Response.value)
}
inline void Response::set_value(const char* value, size_t size) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:stringdb.Response.value)
}
inline ::std::string* Response::mutable_value() {
  set_has_value();
  // @@protoc_insertion_point(field_mutable:stringdb.Response.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Response::release_value() {
  // @@protoc_insertion_point(field_release:stringdb.Response.value)
  clear_has_value();
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Response::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    set_has_value();
  } else {
    clear_has_value();
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:stringdb.Response.value)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace stringdb

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::stringdb::Request_RequestType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::stringdb::Request_RequestType>() {
  return ::stringdb::Request_RequestType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_stringdb_2eproto__INCLUDED
