// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ups.proto

#ifndef PROTOBUF_ups_2eproto__INCLUDED
#define PROTOBUF_ups_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace ups {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ups_2eproto();
void protobuf_AssignDesc_ups_2eproto();
void protobuf_ShutdownFile_ups_2eproto();

class UConnect;
class UConnected;
class UGoPickup;
class UFinished;
class UDeliveryMade;
class UDeliveryLocation;
class UGoDeliver;
class UCommands;
class UResponses;

// ===================================================================

class UConnect : public ::google::protobuf::Message {
 public:
  UConnect();
  virtual ~UConnect();

  UConnect(const UConnect& from);

  inline UConnect& operator=(const UConnect& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UConnect& default_instance();

  void Swap(UConnect* other);

  // implements Message ----------------------------------------------

  UConnect* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UConnect& from);
  void MergeFrom(const UConnect& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 reconnectid = 1;
  inline bool has_reconnectid() const;
  inline void clear_reconnectid();
  static const int kReconnectidFieldNumber = 1;
  inline ::google::protobuf::int64 reconnectid() const;
  inline void set_reconnectid(::google::protobuf::int64 value);

  // optional int32 numtrucksinit = 2;
  inline bool has_numtrucksinit() const;
  inline void clear_numtrucksinit();
  static const int kNumtrucksinitFieldNumber = 2;
  inline ::google::protobuf::int32 numtrucksinit() const;
  inline void set_numtrucksinit(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ups.UConnect)
 private:
  inline void set_has_reconnectid();
  inline void clear_has_reconnectid();
  inline void set_has_numtrucksinit();
  inline void clear_has_numtrucksinit();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 reconnectid_;
  ::google::protobuf::int32 numtrucksinit_;
  friend void  protobuf_AddDesc_ups_2eproto();
  friend void protobuf_AssignDesc_ups_2eproto();
  friend void protobuf_ShutdownFile_ups_2eproto();

  void InitAsDefaultInstance();
  static UConnect* default_instance_;
};
// -------------------------------------------------------------------

class UConnected : public ::google::protobuf::Message {
 public:
  UConnected();
  virtual ~UConnected();

  UConnected(const UConnected& from);

  inline UConnected& operator=(const UConnected& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UConnected& default_instance();

  void Swap(UConnected* other);

  // implements Message ----------------------------------------------

  UConnected* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UConnected& from);
  void MergeFrom(const UConnected& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 worldid = 1;
  inline bool has_worldid() const;
  inline void clear_worldid();
  static const int kWorldidFieldNumber = 1;
  inline ::google::protobuf::int64 worldid() const;
  inline void set_worldid(::google::protobuf::int64 value);

  // optional string error = 2;
  inline bool has_error() const;
  inline void clear_error();
  static const int kErrorFieldNumber = 2;
  inline const ::std::string& error() const;
  inline void set_error(const ::std::string& value);
  inline void set_error(const char* value);
  inline void set_error(const char* value, size_t size);
  inline ::std::string* mutable_error();
  inline ::std::string* release_error();
  inline void set_allocated_error(::std::string* error);

  // @@protoc_insertion_point(class_scope:ups.UConnected)
 private:
  inline void set_has_worldid();
  inline void clear_has_worldid();
  inline void set_has_error();
  inline void clear_has_error();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 worldid_;
  ::std::string* error_;
  friend void  protobuf_AddDesc_ups_2eproto();
  friend void protobuf_AssignDesc_ups_2eproto();
  friend void protobuf_ShutdownFile_ups_2eproto();

  void InitAsDefaultInstance();
  static UConnected* default_instance_;
};
// -------------------------------------------------------------------

class UGoPickup : public ::google::protobuf::Message {
 public:
  UGoPickup();
  virtual ~UGoPickup();

  UGoPickup(const UGoPickup& from);

  inline UGoPickup& operator=(const UGoPickup& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UGoPickup& default_instance();

  void Swap(UGoPickup* other);

  // implements Message ----------------------------------------------

  UGoPickup* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UGoPickup& from);
  void MergeFrom(const UGoPickup& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 truckid = 1;
  inline bool has_truckid() const;
  inline void clear_truckid();
  static const int kTruckidFieldNumber = 1;
  inline ::google::protobuf::int32 truckid() const;
  inline void set_truckid(::google::protobuf::int32 value);

  // required int32 whid = 2;
  inline bool has_whid() const;
  inline void clear_whid();
  static const int kWhidFieldNumber = 2;
  inline ::google::protobuf::int32 whid() const;
  inline void set_whid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ups.UGoPickup)
 private:
  inline void set_has_truckid();
  inline void clear_has_truckid();
  inline void set_has_whid();
  inline void clear_has_whid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 truckid_;
  ::google::protobuf::int32 whid_;
  friend void  protobuf_AddDesc_ups_2eproto();
  friend void protobuf_AssignDesc_ups_2eproto();
  friend void protobuf_ShutdownFile_ups_2eproto();

  void InitAsDefaultInstance();
  static UGoPickup* default_instance_;
};
// -------------------------------------------------------------------

class UFinished : public ::google::protobuf::Message {
 public:
  UFinished();
  virtual ~UFinished();

  UFinished(const UFinished& from);

  inline UFinished& operator=(const UFinished& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UFinished& default_instance();

  void Swap(UFinished* other);

  // implements Message ----------------------------------------------

  UFinished* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UFinished& from);
  void MergeFrom(const UFinished& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 truckid = 1;
  inline bool has_truckid() const;
  inline void clear_truckid();
  static const int kTruckidFieldNumber = 1;
  inline ::google::protobuf::int32 truckid() const;
  inline void set_truckid(::google::protobuf::int32 value);

  // required int32 x = 2;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 2;
  inline ::google::protobuf::int32 x() const;
  inline void set_x(::google::protobuf::int32 value);

  // required int32 y = 3;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 3;
  inline ::google::protobuf::int32 y() const;
  inline void set_y(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ups.UFinished)
 private:
  inline void set_has_truckid();
  inline void clear_has_truckid();
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 truckid_;
  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;
  friend void  protobuf_AddDesc_ups_2eproto();
  friend void protobuf_AssignDesc_ups_2eproto();
  friend void protobuf_ShutdownFile_ups_2eproto();

  void InitAsDefaultInstance();
  static UFinished* default_instance_;
};
// -------------------------------------------------------------------

class UDeliveryMade : public ::google::protobuf::Message {
 public:
  UDeliveryMade();
  virtual ~UDeliveryMade();

  UDeliveryMade(const UDeliveryMade& from);

  inline UDeliveryMade& operator=(const UDeliveryMade& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UDeliveryMade& default_instance();

  void Swap(UDeliveryMade* other);

  // implements Message ----------------------------------------------

  UDeliveryMade* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UDeliveryMade& from);
  void MergeFrom(const UDeliveryMade& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 truckid = 1;
  inline bool has_truckid() const;
  inline void clear_truckid();
  static const int kTruckidFieldNumber = 1;
  inline ::google::protobuf::int32 truckid() const;
  inline void set_truckid(::google::protobuf::int32 value);

  // required int64 packageid = 2;
  inline bool has_packageid() const;
  inline void clear_packageid();
  static const int kPackageidFieldNumber = 2;
  inline ::google::protobuf::int64 packageid() const;
  inline void set_packageid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:ups.UDeliveryMade)
 private:
  inline void set_has_truckid();
  inline void clear_has_truckid();
  inline void set_has_packageid();
  inline void clear_has_packageid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 packageid_;
  ::google::protobuf::int32 truckid_;
  friend void  protobuf_AddDesc_ups_2eproto();
  friend void protobuf_AssignDesc_ups_2eproto();
  friend void protobuf_ShutdownFile_ups_2eproto();

  void InitAsDefaultInstance();
  static UDeliveryMade* default_instance_;
};
// -------------------------------------------------------------------

class UDeliveryLocation : public ::google::protobuf::Message {
 public:
  UDeliveryLocation();
  virtual ~UDeliveryLocation();

  UDeliveryLocation(const UDeliveryLocation& from);

  inline UDeliveryLocation& operator=(const UDeliveryLocation& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UDeliveryLocation& default_instance();

  void Swap(UDeliveryLocation* other);

  // implements Message ----------------------------------------------

  UDeliveryLocation* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UDeliveryLocation& from);
  void MergeFrom(const UDeliveryLocation& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 packageid = 1;
  inline bool has_packageid() const;
  inline void clear_packageid();
  static const int kPackageidFieldNumber = 1;
  inline ::google::protobuf::int64 packageid() const;
  inline void set_packageid(::google::protobuf::int64 value);

  // required int32 x = 2;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 2;
  inline ::google::protobuf::int32 x() const;
  inline void set_x(::google::protobuf::int32 value);

  // required int32 y = 3;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 3;
  inline ::google::protobuf::int32 y() const;
  inline void set_y(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ups.UDeliveryLocation)
 private:
  inline void set_has_packageid();
  inline void clear_has_packageid();
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 packageid_;
  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;
  friend void  protobuf_AddDesc_ups_2eproto();
  friend void protobuf_AssignDesc_ups_2eproto();
  friend void protobuf_ShutdownFile_ups_2eproto();

  void InitAsDefaultInstance();
  static UDeliveryLocation* default_instance_;
};
// -------------------------------------------------------------------

class UGoDeliver : public ::google::protobuf::Message {
 public:
  UGoDeliver();
  virtual ~UGoDeliver();

  UGoDeliver(const UGoDeliver& from);

  inline UGoDeliver& operator=(const UGoDeliver& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UGoDeliver& default_instance();

  void Swap(UGoDeliver* other);

  // implements Message ----------------------------------------------

  UGoDeliver* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UGoDeliver& from);
  void MergeFrom(const UGoDeliver& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 truckid = 1;
  inline bool has_truckid() const;
  inline void clear_truckid();
  static const int kTruckidFieldNumber = 1;
  inline ::google::protobuf::int32 truckid() const;
  inline void set_truckid(::google::protobuf::int32 value);

  // repeated .ups.UDeliveryLocation packages = 2;
  inline int packages_size() const;
  inline void clear_packages();
  static const int kPackagesFieldNumber = 2;
  inline const ::ups::UDeliveryLocation& packages(int index) const;
  inline ::ups::UDeliveryLocation* mutable_packages(int index);
  inline ::ups::UDeliveryLocation* add_packages();
  inline const ::google::protobuf::RepeatedPtrField< ::ups::UDeliveryLocation >&
      packages() const;
  inline ::google::protobuf::RepeatedPtrField< ::ups::UDeliveryLocation >*
      mutable_packages();

  // @@protoc_insertion_point(class_scope:ups.UGoDeliver)
 private:
  inline void set_has_truckid();
  inline void clear_has_truckid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::ups::UDeliveryLocation > packages_;
  ::google::protobuf::int32 truckid_;
  friend void  protobuf_AddDesc_ups_2eproto();
  friend void protobuf_AssignDesc_ups_2eproto();
  friend void protobuf_ShutdownFile_ups_2eproto();

  void InitAsDefaultInstance();
  static UGoDeliver* default_instance_;
};
// -------------------------------------------------------------------

class UCommands : public ::google::protobuf::Message {
 public:
  UCommands();
  virtual ~UCommands();

  UCommands(const UCommands& from);

  inline UCommands& operator=(const UCommands& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UCommands& default_instance();

  void Swap(UCommands* other);

  // implements Message ----------------------------------------------

  UCommands* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UCommands& from);
  void MergeFrom(const UCommands& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ups.UGoDeliver deliveries = 1;
  inline int deliveries_size() const;
  inline void clear_deliveries();
  static const int kDeliveriesFieldNumber = 1;
  inline const ::ups::UGoDeliver& deliveries(int index) const;
  inline ::ups::UGoDeliver* mutable_deliveries(int index);
  inline ::ups::UGoDeliver* add_deliveries();
  inline const ::google::protobuf::RepeatedPtrField< ::ups::UGoDeliver >&
      deliveries() const;
  inline ::google::protobuf::RepeatedPtrField< ::ups::UGoDeliver >*
      mutable_deliveries();

  // repeated .ups.UGoPickup pickups = 2;
  inline int pickups_size() const;
  inline void clear_pickups();
  static const int kPickupsFieldNumber = 2;
  inline const ::ups::UGoPickup& pickups(int index) const;
  inline ::ups::UGoPickup* mutable_pickups(int index);
  inline ::ups::UGoPickup* add_pickups();
  inline const ::google::protobuf::RepeatedPtrField< ::ups::UGoPickup >&
      pickups() const;
  inline ::google::protobuf::RepeatedPtrField< ::ups::UGoPickup >*
      mutable_pickups();

  // optional uint32 simspeed = 3;
  inline bool has_simspeed() const;
  inline void clear_simspeed();
  static const int kSimspeedFieldNumber = 3;
  inline ::google::protobuf::uint32 simspeed() const;
  inline void set_simspeed(::google::protobuf::uint32 value);

  // optional bool disconnect = 4;
  inline bool has_disconnect() const;
  inline void clear_disconnect();
  static const int kDisconnectFieldNumber = 4;
  inline bool disconnect() const;
  inline void set_disconnect(bool value);

  // @@protoc_insertion_point(class_scope:ups.UCommands)
 private:
  inline void set_has_simspeed();
  inline void clear_has_simspeed();
  inline void set_has_disconnect();
  inline void clear_has_disconnect();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::ups::UGoDeliver > deliveries_;
  ::google::protobuf::RepeatedPtrField< ::ups::UGoPickup > pickups_;
  ::google::protobuf::uint32 simspeed_;
  bool disconnect_;
  friend void  protobuf_AddDesc_ups_2eproto();
  friend void protobuf_AssignDesc_ups_2eproto();
  friend void protobuf_ShutdownFile_ups_2eproto();

  void InitAsDefaultInstance();
  static UCommands* default_instance_;
};
// -------------------------------------------------------------------

class UResponses : public ::google::protobuf::Message {
 public:
  UResponses();
  virtual ~UResponses();

  UResponses(const UResponses& from);

  inline UResponses& operator=(const UResponses& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UResponses& default_instance();

  void Swap(UResponses* other);

  // implements Message ----------------------------------------------

  UResponses* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UResponses& from);
  void MergeFrom(const UResponses& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ups.UFinished completions = 1;
  inline int completions_size() const;
  inline void clear_completions();
  static const int kCompletionsFieldNumber = 1;
  inline const ::ups::UFinished& completions(int index) const;
  inline ::ups::UFinished* mutable_completions(int index);
  inline ::ups::UFinished* add_completions();
  inline const ::google::protobuf::RepeatedPtrField< ::ups::UFinished >&
      completions() const;
  inline ::google::protobuf::RepeatedPtrField< ::ups::UFinished >*
      mutable_completions();

  // repeated .ups.UDeliveryMade delivered = 2;
  inline int delivered_size() const;
  inline void clear_delivered();
  static const int kDeliveredFieldNumber = 2;
  inline const ::ups::UDeliveryMade& delivered(int index) const;
  inline ::ups::UDeliveryMade* mutable_delivered(int index);
  inline ::ups::UDeliveryMade* add_delivered();
  inline const ::google::protobuf::RepeatedPtrField< ::ups::UDeliveryMade >&
      delivered() const;
  inline ::google::protobuf::RepeatedPtrField< ::ups::UDeliveryMade >*
      mutable_delivered();

  // optional string error = 3;
  inline bool has_error() const;
  inline void clear_error();
  static const int kErrorFieldNumber = 3;
  inline const ::std::string& error() const;
  inline void set_error(const ::std::string& value);
  inline void set_error(const char* value);
  inline void set_error(const char* value, size_t size);
  inline ::std::string* mutable_error();
  inline ::std::string* release_error();
  inline void set_allocated_error(::std::string* error);

  // optional bool finished = 4;
  inline bool has_finished() const;
  inline void clear_finished();
  static const int kFinishedFieldNumber = 4;
  inline bool finished() const;
  inline void set_finished(bool value);

  // @@protoc_insertion_point(class_scope:ups.UResponses)
 private:
  inline void set_has_error();
  inline void clear_has_error();
  inline void set_has_finished();
  inline void clear_has_finished();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::ups::UFinished > completions_;
  ::google::protobuf::RepeatedPtrField< ::ups::UDeliveryMade > delivered_;
  ::std::string* error_;
  bool finished_;
  friend void  protobuf_AddDesc_ups_2eproto();
  friend void protobuf_AssignDesc_ups_2eproto();
  friend void protobuf_ShutdownFile_ups_2eproto();

  void InitAsDefaultInstance();
  static UResponses* default_instance_;
};
// ===================================================================


// ===================================================================

// UConnect

// optional int64 reconnectid = 1;
inline bool UConnect::has_reconnectid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UConnect::set_has_reconnectid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UConnect::clear_has_reconnectid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UConnect::clear_reconnectid() {
  reconnectid_ = GOOGLE_LONGLONG(0);
  clear_has_reconnectid();
}
inline ::google::protobuf::int64 UConnect::reconnectid() const {
  // @@protoc_insertion_point(field_get:ups.UConnect.reconnectid)
  return reconnectid_;
}
inline void UConnect::set_reconnectid(::google::protobuf::int64 value) {
  set_has_reconnectid();
  reconnectid_ = value;
  // @@protoc_insertion_point(field_set:ups.UConnect.reconnectid)
}

// optional int32 numtrucksinit = 2;
inline bool UConnect::has_numtrucksinit() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UConnect::set_has_numtrucksinit() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UConnect::clear_has_numtrucksinit() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UConnect::clear_numtrucksinit() {
  numtrucksinit_ = 0;
  clear_has_numtrucksinit();
}
inline ::google::protobuf::int32 UConnect::numtrucksinit() const {
  // @@protoc_insertion_point(field_get:ups.UConnect.numtrucksinit)
  return numtrucksinit_;
}
inline void UConnect::set_numtrucksinit(::google::protobuf::int32 value) {
  set_has_numtrucksinit();
  numtrucksinit_ = value;
  // @@protoc_insertion_point(field_set:ups.UConnect.numtrucksinit)
}

// -------------------------------------------------------------------

// UConnected

// required int64 worldid = 1;
inline bool UConnected::has_worldid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UConnected::set_has_worldid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UConnected::clear_has_worldid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UConnected::clear_worldid() {
  worldid_ = GOOGLE_LONGLONG(0);
  clear_has_worldid();
}
inline ::google::protobuf::int64 UConnected::worldid() const {
  // @@protoc_insertion_point(field_get:ups.UConnected.worldid)
  return worldid_;
}
inline void UConnected::set_worldid(::google::protobuf::int64 value) {
  set_has_worldid();
  worldid_ = value;
  // @@protoc_insertion_point(field_set:ups.UConnected.worldid)
}

// optional string error = 2;
inline bool UConnected::has_error() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UConnected::set_has_error() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UConnected::clear_has_error() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UConnected::clear_error() {
  if (error_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    error_->clear();
  }
  clear_has_error();
}
inline const ::std::string& UConnected::error() const {
  // @@protoc_insertion_point(field_get:ups.UConnected.error)
  return *error_;
}
inline void UConnected::set_error(const ::std::string& value) {
  set_has_error();
  if (error_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    error_ = new ::std::string;
  }
  error_->assign(value);
  // @@protoc_insertion_point(field_set:ups.UConnected.error)
}
inline void UConnected::set_error(const char* value) {
  set_has_error();
  if (error_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    error_ = new ::std::string;
  }
  error_->assign(value);
  // @@protoc_insertion_point(field_set_char:ups.UConnected.error)
}
inline void UConnected::set_error(const char* value, size_t size) {
  set_has_error();
  if (error_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    error_ = new ::std::string;
  }
  error_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ups.UConnected.error)
}
inline ::std::string* UConnected::mutable_error() {
  set_has_error();
  if (error_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    error_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:ups.UConnected.error)
  return error_;
}
inline ::std::string* UConnected::release_error() {
  clear_has_error();
  if (error_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = error_;
    error_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void UConnected::set_allocated_error(::std::string* error) {
  if (error_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete error_;
  }
  if (error) {
    set_has_error();
    error_ = error;
  } else {
    clear_has_error();
    error_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:ups.UConnected.error)
}

// -------------------------------------------------------------------

// UGoPickup

// required int32 truckid = 1;
inline bool UGoPickup::has_truckid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UGoPickup::set_has_truckid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UGoPickup::clear_has_truckid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UGoPickup::clear_truckid() {
  truckid_ = 0;
  clear_has_truckid();
}
inline ::google::protobuf::int32 UGoPickup::truckid() const {
  // @@protoc_insertion_point(field_get:ups.UGoPickup.truckid)
  return truckid_;
}
inline void UGoPickup::set_truckid(::google::protobuf::int32 value) {
  set_has_truckid();
  truckid_ = value;
  // @@protoc_insertion_point(field_set:ups.UGoPickup.truckid)
}

// required int32 whid = 2;
inline bool UGoPickup::has_whid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UGoPickup::set_has_whid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UGoPickup::clear_has_whid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UGoPickup::clear_whid() {
  whid_ = 0;
  clear_has_whid();
}
inline ::google::protobuf::int32 UGoPickup::whid() const {
  // @@protoc_insertion_point(field_get:ups.UGoPickup.whid)
  return whid_;
}
inline void UGoPickup::set_whid(::google::protobuf::int32 value) {
  set_has_whid();
  whid_ = value;
  // @@protoc_insertion_point(field_set:ups.UGoPickup.whid)
}

// -------------------------------------------------------------------

// UFinished

// required int32 truckid = 1;
inline bool UFinished::has_truckid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UFinished::set_has_truckid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UFinished::clear_has_truckid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UFinished::clear_truckid() {
  truckid_ = 0;
  clear_has_truckid();
}
inline ::google::protobuf::int32 UFinished::truckid() const {
  // @@protoc_insertion_point(field_get:ups.UFinished.truckid)
  return truckid_;
}
inline void UFinished::set_truckid(::google::protobuf::int32 value) {
  set_has_truckid();
  truckid_ = value;
  // @@protoc_insertion_point(field_set:ups.UFinished.truckid)
}

// required int32 x = 2;
inline bool UFinished::has_x() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UFinished::set_has_x() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UFinished::clear_has_x() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UFinished::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline ::google::protobuf::int32 UFinished::x() const {
  // @@protoc_insertion_point(field_get:ups.UFinished.x)
  return x_;
}
inline void UFinished::set_x(::google::protobuf::int32 value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:ups.UFinished.x)
}

// required int32 y = 3;
inline bool UFinished::has_y() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void UFinished::set_has_y() {
  _has_bits_[0] |= 0x00000004u;
}
inline void UFinished::clear_has_y() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void UFinished::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline ::google::protobuf::int32 UFinished::y() const {
  // @@protoc_insertion_point(field_get:ups.UFinished.y)
  return y_;
}
inline void UFinished::set_y(::google::protobuf::int32 value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:ups.UFinished.y)
}

// -------------------------------------------------------------------

// UDeliveryMade

// required int32 truckid = 1;
inline bool UDeliveryMade::has_truckid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UDeliveryMade::set_has_truckid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UDeliveryMade::clear_has_truckid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UDeliveryMade::clear_truckid() {
  truckid_ = 0;
  clear_has_truckid();
}
inline ::google::protobuf::int32 UDeliveryMade::truckid() const {
  // @@protoc_insertion_point(field_get:ups.UDeliveryMade.truckid)
  return truckid_;
}
inline void UDeliveryMade::set_truckid(::google::protobuf::int32 value) {
  set_has_truckid();
  truckid_ = value;
  // @@protoc_insertion_point(field_set:ups.UDeliveryMade.truckid)
}

// required int64 packageid = 2;
inline bool UDeliveryMade::has_packageid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UDeliveryMade::set_has_packageid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UDeliveryMade::clear_has_packageid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UDeliveryMade::clear_packageid() {
  packageid_ = GOOGLE_LONGLONG(0);
  clear_has_packageid();
}
inline ::google::protobuf::int64 UDeliveryMade::packageid() const {
  // @@protoc_insertion_point(field_get:ups.UDeliveryMade.packageid)
  return packageid_;
}
inline void UDeliveryMade::set_packageid(::google::protobuf::int64 value) {
  set_has_packageid();
  packageid_ = value;
  // @@protoc_insertion_point(field_set:ups.UDeliveryMade.packageid)
}

// -------------------------------------------------------------------

// UDeliveryLocation

// required int64 packageid = 1;
inline bool UDeliveryLocation::has_packageid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UDeliveryLocation::set_has_packageid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UDeliveryLocation::clear_has_packageid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UDeliveryLocation::clear_packageid() {
  packageid_ = GOOGLE_LONGLONG(0);
  clear_has_packageid();
}
inline ::google::protobuf::int64 UDeliveryLocation::packageid() const {
  // @@protoc_insertion_point(field_get:ups.UDeliveryLocation.packageid)
  return packageid_;
}
inline void UDeliveryLocation::set_packageid(::google::protobuf::int64 value) {
  set_has_packageid();
  packageid_ = value;
  // @@protoc_insertion_point(field_set:ups.UDeliveryLocation.packageid)
}

// required int32 x = 2;
inline bool UDeliveryLocation::has_x() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UDeliveryLocation::set_has_x() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UDeliveryLocation::clear_has_x() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UDeliveryLocation::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline ::google::protobuf::int32 UDeliveryLocation::x() const {
  // @@protoc_insertion_point(field_get:ups.UDeliveryLocation.x)
  return x_;
}
inline void UDeliveryLocation::set_x(::google::protobuf::int32 value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:ups.UDeliveryLocation.x)
}

// required int32 y = 3;
inline bool UDeliveryLocation::has_y() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void UDeliveryLocation::set_has_y() {
  _has_bits_[0] |= 0x00000004u;
}
inline void UDeliveryLocation::clear_has_y() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void UDeliveryLocation::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline ::google::protobuf::int32 UDeliveryLocation::y() const {
  // @@protoc_insertion_point(field_get:ups.UDeliveryLocation.y)
  return y_;
}
inline void UDeliveryLocation::set_y(::google::protobuf::int32 value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:ups.UDeliveryLocation.y)
}

// -------------------------------------------------------------------

// UGoDeliver

// required int32 truckid = 1;
inline bool UGoDeliver::has_truckid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UGoDeliver::set_has_truckid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UGoDeliver::clear_has_truckid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UGoDeliver::clear_truckid() {
  truckid_ = 0;
  clear_has_truckid();
}
inline ::google::protobuf::int32 UGoDeliver::truckid() const {
  // @@protoc_insertion_point(field_get:ups.UGoDeliver.truckid)
  return truckid_;
}
inline void UGoDeliver::set_truckid(::google::protobuf::int32 value) {
  set_has_truckid();
  truckid_ = value;
  // @@protoc_insertion_point(field_set:ups.UGoDeliver.truckid)
}

// repeated .ups.UDeliveryLocation packages = 2;
inline int UGoDeliver::packages_size() const {
  return packages_.size();
}
inline void UGoDeliver::clear_packages() {
  packages_.Clear();
}
inline const ::ups::UDeliveryLocation& UGoDeliver::packages(int index) const {
  // @@protoc_insertion_point(field_get:ups.UGoDeliver.packages)
  return packages_.Get(index);
}
inline ::ups::UDeliveryLocation* UGoDeliver::mutable_packages(int index) {
  // @@protoc_insertion_point(field_mutable:ups.UGoDeliver.packages)
  return packages_.Mutable(index);
}
inline ::ups::UDeliveryLocation* UGoDeliver::add_packages() {
  // @@protoc_insertion_point(field_add:ups.UGoDeliver.packages)
  return packages_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ups::UDeliveryLocation >&
UGoDeliver::packages() const {
  // @@protoc_insertion_point(field_list:ups.UGoDeliver.packages)
  return packages_;
}
inline ::google::protobuf::RepeatedPtrField< ::ups::UDeliveryLocation >*
UGoDeliver::mutable_packages() {
  // @@protoc_insertion_point(field_mutable_list:ups.UGoDeliver.packages)
  return &packages_;
}

// -------------------------------------------------------------------

// UCommands

// repeated .ups.UGoDeliver deliveries = 1;
inline int UCommands::deliveries_size() const {
  return deliveries_.size();
}
inline void UCommands::clear_deliveries() {
  deliveries_.Clear();
}
inline const ::ups::UGoDeliver& UCommands::deliveries(int index) const {
  // @@protoc_insertion_point(field_get:ups.UCommands.deliveries)
  return deliveries_.Get(index);
}
inline ::ups::UGoDeliver* UCommands::mutable_deliveries(int index) {
  // @@protoc_insertion_point(field_mutable:ups.UCommands.deliveries)
  return deliveries_.Mutable(index);
}
inline ::ups::UGoDeliver* UCommands::add_deliveries() {
  // @@protoc_insertion_point(field_add:ups.UCommands.deliveries)
  return deliveries_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ups::UGoDeliver >&
UCommands::deliveries() const {
  // @@protoc_insertion_point(field_list:ups.UCommands.deliveries)
  return deliveries_;
}
inline ::google::protobuf::RepeatedPtrField< ::ups::UGoDeliver >*
UCommands::mutable_deliveries() {
  // @@protoc_insertion_point(field_mutable_list:ups.UCommands.deliveries)
  return &deliveries_;
}

// repeated .ups.UGoPickup pickups = 2;
inline int UCommands::pickups_size() const {
  return pickups_.size();
}
inline void UCommands::clear_pickups() {
  pickups_.Clear();
}
inline const ::ups::UGoPickup& UCommands::pickups(int index) const {
  // @@protoc_insertion_point(field_get:ups.UCommands.pickups)
  return pickups_.Get(index);
}
inline ::ups::UGoPickup* UCommands::mutable_pickups(int index) {
  // @@protoc_insertion_point(field_mutable:ups.UCommands.pickups)
  return pickups_.Mutable(index);
}
inline ::ups::UGoPickup* UCommands::add_pickups() {
  // @@protoc_insertion_point(field_add:ups.UCommands.pickups)
  return pickups_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ups::UGoPickup >&
UCommands::pickups() const {
  // @@protoc_insertion_point(field_list:ups.UCommands.pickups)
  return pickups_;
}
inline ::google::protobuf::RepeatedPtrField< ::ups::UGoPickup >*
UCommands::mutable_pickups() {
  // @@protoc_insertion_point(field_mutable_list:ups.UCommands.pickups)
  return &pickups_;
}

// optional uint32 simspeed = 3;
inline bool UCommands::has_simspeed() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void UCommands::set_has_simspeed() {
  _has_bits_[0] |= 0x00000004u;
}
inline void UCommands::clear_has_simspeed() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void UCommands::clear_simspeed() {
  simspeed_ = 0u;
  clear_has_simspeed();
}
inline ::google::protobuf::uint32 UCommands::simspeed() const {
  // @@protoc_insertion_point(field_get:ups.UCommands.simspeed)
  return simspeed_;
}
inline void UCommands::set_simspeed(::google::protobuf::uint32 value) {
  set_has_simspeed();
  simspeed_ = value;
  // @@protoc_insertion_point(field_set:ups.UCommands.simspeed)
}

// optional bool disconnect = 4;
inline bool UCommands::has_disconnect() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void UCommands::set_has_disconnect() {
  _has_bits_[0] |= 0x00000008u;
}
inline void UCommands::clear_has_disconnect() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void UCommands::clear_disconnect() {
  disconnect_ = false;
  clear_has_disconnect();
}
inline bool UCommands::disconnect() const {
  // @@protoc_insertion_point(field_get:ups.UCommands.disconnect)
  return disconnect_;
}
inline void UCommands::set_disconnect(bool value) {
  set_has_disconnect();
  disconnect_ = value;
  // @@protoc_insertion_point(field_set:ups.UCommands.disconnect)
}

// -------------------------------------------------------------------

// UResponses

// repeated .ups.UFinished completions = 1;
inline int UResponses::completions_size() const {
  return completions_.size();
}
inline void UResponses::clear_completions() {
  completions_.Clear();
}
inline const ::ups::UFinished& UResponses::completions(int index) const {
  // @@protoc_insertion_point(field_get:ups.UResponses.completions)
  return completions_.Get(index);
}
inline ::ups::UFinished* UResponses::mutable_completions(int index) {
  // @@protoc_insertion_point(field_mutable:ups.UResponses.completions)
  return completions_.Mutable(index);
}
inline ::ups::UFinished* UResponses::add_completions() {
  // @@protoc_insertion_point(field_add:ups.UResponses.completions)
  return completions_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ups::UFinished >&
UResponses::completions() const {
  // @@protoc_insertion_point(field_list:ups.UResponses.completions)
  return completions_;
}
inline ::google::protobuf::RepeatedPtrField< ::ups::UFinished >*
UResponses::mutable_completions() {
  // @@protoc_insertion_point(field_mutable_list:ups.UResponses.completions)
  return &completions_;
}

// repeated .ups.UDeliveryMade delivered = 2;
inline int UResponses::delivered_size() const {
  return delivered_.size();
}
inline void UResponses::clear_delivered() {
  delivered_.Clear();
}
inline const ::ups::UDeliveryMade& UResponses::delivered(int index) const {
  // @@protoc_insertion_point(field_get:ups.UResponses.delivered)
  return delivered_.Get(index);
}
inline ::ups::UDeliveryMade* UResponses::mutable_delivered(int index) {
  // @@protoc_insertion_point(field_mutable:ups.UResponses.delivered)
  return delivered_.Mutable(index);
}
inline ::ups::UDeliveryMade* UResponses::add_delivered() {
  // @@protoc_insertion_point(field_add:ups.UResponses.delivered)
  return delivered_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ups::UDeliveryMade >&
UResponses::delivered() const {
  // @@protoc_insertion_point(field_list:ups.UResponses.delivered)
  return delivered_;
}
inline ::google::protobuf::RepeatedPtrField< ::ups::UDeliveryMade >*
UResponses::mutable_delivered() {
  // @@protoc_insertion_point(field_mutable_list:ups.UResponses.delivered)
  return &delivered_;
}

// optional string error = 3;
inline bool UResponses::has_error() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void UResponses::set_has_error() {
  _has_bits_[0] |= 0x00000004u;
}
inline void UResponses::clear_has_error() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void UResponses::clear_error() {
  if (error_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    error_->clear();
  }
  clear_has_error();
}
inline const ::std::string& UResponses::error() const {
  // @@protoc_insertion_point(field_get:ups.UResponses.error)
  return *error_;
}
inline void UResponses::set_error(const ::std::string& value) {
  set_has_error();
  if (error_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    error_ = new ::std::string;
  }
  error_->assign(value);
  // @@protoc_insertion_point(field_set:ups.UResponses.error)
}
inline void UResponses::set_error(const char* value) {
  set_has_error();
  if (error_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    error_ = new ::std::string;
  }
  error_->assign(value);
  // @@protoc_insertion_point(field_set_char:ups.UResponses.error)
}
inline void UResponses::set_error(const char* value, size_t size) {
  set_has_error();
  if (error_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    error_ = new ::std::string;
  }
  error_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ups.UResponses.error)
}
inline ::std::string* UResponses::mutable_error() {
  set_has_error();
  if (error_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    error_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:ups.UResponses.error)
  return error_;
}
inline ::std::string* UResponses::release_error() {
  clear_has_error();
  if (error_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = error_;
    error_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void UResponses::set_allocated_error(::std::string* error) {
  if (error_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete error_;
  }
  if (error) {
    set_has_error();
    error_ = error;
  } else {
    clear_has_error();
    error_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:ups.UResponses.error)
}

// optional bool finished = 4;
inline bool UResponses::has_finished() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void UResponses::set_has_finished() {
  _has_bits_[0] |= 0x00000008u;
}
inline void UResponses::clear_has_finished() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void UResponses::clear_finished() {
  finished_ = false;
  clear_has_finished();
}
inline bool UResponses::finished() const {
  // @@protoc_insertion_point(field_get:ups.UResponses.finished)
  return finished_;
}
inline void UResponses::set_finished(bool value) {
  set_has_finished();
  finished_ = value;
  // @@protoc_insertion_point(field_set:ups.UResponses.finished)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ups

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ups_2eproto__INCLUDED
