# Generated by Django 2.0.4 on 2018-04-26 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('tracking_num', models.IntegerField(unique=True)),
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('wh_id', models.IntegerField(null=True)),
                ('des_x', models.IntegerField(null=True)),
                ('des_y', models.IntegerField(null=True)),
                ('status', models.SmallIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('first_item', models.CharField(max_length=50, null=True)),
                ('item_num', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='trucks',
            fields=[
                ('truck_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=0)),
                ('xloction', models.IntegerField(blank=True, null=True)),
                ('yloction', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='warehouses',
            fields=[
                ('wh_id', models.IntegerField(primary_key=True, serialize=False)),
                ('xlocation', models.IntegerField()),
                ('ylocation', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.trucks'),
        ),
    ]
