# Generated by Django 2.0.2 on 2018-04-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='warehouses',
            fields=[
                ('wh_id', models.IntegerField(primary_key=True, serialize=False)),
                ('xlocation', models.IntegerField()),
                ('ylocation', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
