# Generated by Django 2.0.2 on 2018-04-14 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shipment',
            new_name='shipments',
        ),
        migrations.RenameModel(
            old_name='truck',
            new_name='trucks',
        ),
    ]
