# Generated by Django 2.0.2 on 2018-04-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20180414_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trucks',
            name='xLoction',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='yLoction',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
