# Generated by Django 2.0.2 on 2018-04-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20180414_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipments',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
