# Generated by Django 2.0.2 on 2018-04-20 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20180413_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('tracking_num', models.IntegerField(unique=True)),
                ('order_id', models.IntegerField(default=-1, primary_key=True, serialize=False)),
                ('wh_id', models.IntegerField(null=True)),
                ('des_x', models.IntegerField(null=True)),
                ('des_y', models.IntegerField(null=True)),
                ('status', models.SmallIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='shipments',
            name='truck',
        ),
        migrations.RemoveField(
            model_name='trucks',
            name='id',
        ),
        migrations.AddField(
            model_name='trucks',
            name='truck_id',
            field=models.IntegerField(default=-1, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='shipments',
        ),
        migrations.AddField(
            model_name='orders',
            name='truck_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.trucks'),
        ),
        migrations.AddField(
            model_name='items',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.orders'),
        ),
    ]
