# Generated by Django 2.0.2 on 2018-04-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20180420_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='truck_id',
            new_name='truck',
        ),
        migrations.AlterField(
            model_name='trucks',
            name='truck_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
