# Generated by Django 2.0.2 on 2018-04-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_orders_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trucks',
            old_name='xLoction',
            new_name='xloction',
        ),
        migrations.RenameField(
            model_name='trucks',
            old_name='yLoction',
            new_name='yloction',
        ),
    ]
