version: '2'

services:
  world:
    build: ./Docker
    volumes:
      - ./Docker:/usr/src/app
    ports:
      - 12345:12345
      - 23456:23456
  db:
      image: postgres
      volumes:
            - data-volume:/var/lib/postgresql/data
  web-init:
      build: ./web-app
      command: /code/initserver.sh
      volumes:
        - ./web-app:/code
      depends_on:
        - db
  web:
      build: ./web-app
      user: nobody
      command: /code/runserver.sh
      volumes:
        - ./web-app:/code
      expose:
        - "8000"
      depends_on:
        - web-init
  nginx:
     image: nginx:latest
     ports:
       - "8000:8000"
     volumes:
       - ./nginx/config:/etc/nginx/conf.d
     depends_on:
       - web
  ups:
     build: ./ups_server
     command: bash -c "sleep 5 && ./server"
     volumes:
       - ./ups_server:/code
     depends_on:
       - web
       - world
volumes:
   data-volume: 